### ISSUE TITLE
[Feature Request] Scan for server headers

### ISSUE THREAD

**Issue by dreizehnutters** [scnr/installer#10]
Hi,
thanks for sharing the tool, i like it sofar!

The engine does not register any server headers, sent by a server to a client (which leaks infos)

I would commit a PR, but i couldnt find the source repo ?

**Comment by Zapotek** [comment]
Hello,

Source repo is private but I'll add this feature.

Cheers

**Comment by Zapotek** [comment]
Done!

You can see it running be re-installing.
