### ISSUE TITLE
Error and Also script has expired Issue

### ISSUE THREAD

**Issue by ghost** [scnr/installer#14]
─[~/scnr-1.0dev-1.0dev-1.0dev/bin]
└──╼ $ ./scnr
Traceback (most recent call last):
	5: from /home/user/scnr-1.0dev-1.0dev-1.0dev/bin/../.system/gems/bin/scnr:25:in `<main>'
	4: from /home/user/scnr-1.0dev-1.0dev-1.0dev/bin/../.system/gems/bin/scnr:25:in `load'
	3: from /home/user/scnr-1.0dev-1.0dev-1.0dev/.system/gems/gems/scnr-ui-cli-1.0dev/bin/scnr:10:in `<top (required)>'
	2: from /home/user/scnr-1.0dev-1.0dev-1.0dev/.system/gems/gems/scnr-ui-cli-1.0dev/bin/scnr:10:in `require_relative'
	1: from /home/user/scnr-1.0dev-1.0dev-1.0dev/.system/gems/gems/scnr-ui-cli-1.0dev/lib/scnr/ui/cli.rb:2:in `<top (required)>'
/home/user/scnr-1.0dev-1.0dev-1.0dev/.system/gems/gems/scnr-ui-cli-1.0dev/lib/scnr/ui/cli.rb:2:in `RGLoader_load': RubyEncoder Loader - This protected script has expired. Please contact the author of the script about this problem. Error code [09] (RGLoaderError)

**Comment by ShahidAkhterSec** [comment]
bash -c "$(curl -sSL https://raw.githubusercontent.com/scnr/installer/main/install.sh)"

                      SCNR installer
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         by Tasos Laskos <tasos.laskos@ecsypno.com>
-------------------------------------------------------------------------

(1/2) Google Chrome
   * Downloading...done.
   * Installing...done.

(2/2) SCNR
   * Downloading...done.
   * Installing...done.
   * Setting up the DB...Installation failed, check /home/user/scnr.install.log for details.

**Comment by ShahidAkhterSec** [comment]
it:1 https://deb.parrot.sh/parrot lts InRelease
Hit:2 https://deb.parrot.sh/parrot parrot InRelease
Hit:3 https://deb.parrot.sh/direct/parrot parrot-security InRelease
Hit:4 https://deb.parrot.sh/parrot parrot-backports InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libu2f-udev
The following NEW packages will be installed:
  google-chrome-stable libu2f-udev
0 upgraded, 2 newly installed, 0 to remove and 58 not upgraded.
Need to get 6,300 B/93.3 MB of archives.
After this operation, 314 MB of additional disk space will be used.
Get:1 https://deb.parrot.sh/parrot lts/main amd64 libu2f-udev all 1.1.10-3 [6,300 B]
Get:2 /tmp/google-chrome.deb google-chrome-stable amd64 107.0.5304.110-1 [93.3 MB]
Fetched 6,300 B in 1s (5,220 B/s)
Selecting previously unselected package google-chrome-stable.

(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 453829 files and directories currently installed.)

Preparing to unpack /tmp/google-chrome.deb ...

Unpacking google-chrome-stable (107.0.5304.110-1) ...

Selecting previously unselected package libu2f-udev.

Preparing to unpack .../libu2f-udev_1.1.10-3_all.deb ...

Unpacking libu2f-udev (1.1.10-3) ...

Setting up google-chrome-stable (107.0.5304.110-1) ...

update-alternatives: using /usr/bin/google-chrome-stable to provide /usr/bin/x-www-browser (x-www-browser) in auto mode

update-alternatives: using /usr/bin/google-chrome-stable to provide /usr/bin/gnome-www-browser (gnome-www-browser) in auto mode

update-alternatives: using /usr/bin/google-chrome-stable to provide /usr/bin/google-chrome (google-chrome) in auto mode

Setting up libu2f-udev (1.1.10-3) ...

Processing triggers for menu (2.1.48) ...

Processing triggers for mailcap (3.69) ...

Processing triggers for bamfdaemon (0.5.4-2) ...

Rebuilding /usr/share/applications/bamf-2.index...

Processing triggers for desktop-file-utils (0.26-1) ...

Processing triggers for man-db (2.10.1-1~bpo11+1) ...

Scanning application launchers
Removing duplicate launchers or broken launchers
Launchers are updated
mv: cannot stat '/home/user/scnr-1.0dev-1.0dev-1.0dev': No such file or directory
rake aborted!
RGLoaderError: RubyEncoder Loader - This protected script has expired. Please contact the author of the script about this problem. Error code [09]
/home/user/scnr-1.0dev-1.0dev-1.0dev/.system/scnr-ui-pro/config/application.rb:2:in `RGLoader_load'
/home/user/scnr-1.0dev-1.0dev-1.0dev/.system/scnr-ui-pro/config/application.rb:2:in `<top (required)>'
/home/user/scnr-1.0dev-1.0dev-1.0dev/.system/scnr-ui-pro/Rakefile:4:in `<top (required)>'
/home/user/scnr-1.0dev-1.0dev-1.0dev/.system/gems/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)

**Comment by Sander-VdB** [comment]
Exactly the same issue here.

**Comment by rohantakke** [comment]
+1

**Comment by wowter-code** [comment]
Same issue for me:

`RGLoaderError: RubyEncoder Loader - This protected script has expired. Please contact the author of the script about this problem. Error code [09]
/home/kali/scnr-1.0dev-1.0dev-1.0dev/.system/scnr-ui-pro/config/application.rb:2:in `RGLoader_load'
/home/kali/scnr-1.0dev-1.0dev-1.0dev/.system/scnr-ui-pro/config/application.rb:2:in `<top (required)>'
/home/kali/scnr-1.0dev-1.0dev-1.0dev/.system/scnr-ui-pro/Rakefile:4:in `<top (required)>'
/home/kali/scnr-1.0dev-1.0dev-1.0dev/.system/gems/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)`

**Comment by Davidluna19** [comment]
+1

**Comment by konn-neko** [comment]
@Zapotek it happened

**Comment by CGitSnir** [comment]
Same issue for me as well. Any updates?

**Comment by xelerated** [comment]
And still no fix, deleted.

**Comment by anubis159951** [comment]
Same error

**Comment by anubis159951** [comment]
Same issue

**Comment by Zapotek** [comment]
Fixed.
