### ISSUE TITLE
Installation failed 

### ISSUE THREAD

**Issue by mdelnegro** [scnr/installer#16]
I have encountered a problem with the installation of the new ecsypno PEN-TEST Software.
 At the first line I have the following error: 
 **RGLoaderError: RubyEncoder Loader - This protected script has expired. Please contact the author of the script about this problem. Error code [09]**
Can you help me with this problem? 
Thanks, best regards.

**Comment by reddude21** [comment]
same error... any fix?

**Comment by Zapotek** [comment]
Fixed.
