### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by lordofdeceit** [scnr/installer#17]
Installation does not go on after install of google chrome, running on kali 2022, also failed on linode

**Comment by lordofdeceit** [comment]
scnr-1.0dev-1.0dev-1.0dev': No such file or directory
rake aborted!
RGLoaderError: RubyEncoder Loader - This protected script has expired. Please contact the author of the script about this problem. Error code [09] the error I get

**Comment by reddude21** [comment]
Getting same error running on Ubuntu
Any fix?

**Comment by Zapotek** [comment]
Fixed.
