### ISSUE TITLE
installation failed on Ubuntu 20.04.6

### ISSUE THREAD

**Issue by dnisqa** [scnr/installer#18]
OS: Ubuntu 20.04.6
Kernel: GNU/Linux 5.4.0-146-generic x86_64
Glibc version: 2.31 (Ubuntu 20.04.6 embed default version)

**_Install fail information:_**
google-chrome-stable is already the newest version (111.0.5563.146-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
ruby: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ruby)
ruby: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /home/itest/scnr-1.0dev-1.0dev-1.0dev/bin/../.system/usr/lib/libruby.so.
2.7)
ruby: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/itest/scnr-1.0dev-1.0dev-1.0dev/bin/../.system/usr/lib/libruby.so.
2.7)
ruby: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/itest/scnr-1.0dev-1.0dev-1.0dev/bin/../.system/usr/lib/libruby.so.
2.7)
ruby: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/itest/scnr-1.0dev-1.0dev-1.0dev/bin/../.system/usr/lib/libruby.so.
2.7)
~

**Comment by Zapotek** [comment]
Hello,

You need libc >= 2.35.

You can fix this issue by updating your system.

Cheers
