### ISSUE TITLE
Error when trying to run a scan

### ISSUE THREAD

**Issue by Mettthew** [scnr/installer#24]
hello everyone,

I am trying to study different scanners for my undergraduate studies and came across SCNR, I am trying to use it in my Kali Linux virtual machine and wanted to test it with a Metasploitable machine.

The problem I am running into is that when I try to use ./scnr or the API to scan the target, what I get is the following error:

[*] Initializing...
 [*] Preparing plugins...
 [*] ... done.
 [*] BrowserPool: Initializing 1 Chrome browsers...
#<Thread:0x00007f64ac14f100 /home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser_pool.rb:493 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        17: from /home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser_pool.rb:494:in `block (2 levels) in initialize_workers'
        16: from /home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser_pool.rb:494:in `new'
        15: from /home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser_pool/worker.rb:56:in `initialize'
        14: from /home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/support/mixins/spec_instances.rb:64:in `initialize'
        13: from /home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser.rb:62:in `initialize'
        12: from /home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/parts/snapshots.rb:40:in `initialize'
        11: from /home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/parts/http.rb:38:in `initialize'
        10: from /home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/parts/navigation.rb:39:in `initialize'
         9: from /home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/parts/engine.rb:36:in `initialize'
         8: from /home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/parts/engine.rb:36:in `new'
         7: from /home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/support/mixins/spec_instances.rb:64:in `initialize'
         6: from /home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base.rb:85:in `initialize'
         5: from /home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base.rb:124:in `start'
         4: from /home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base/parts/webdriver.rb:94:in `start_webdriver'
         3: from /home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base/parts/webdriver.rb:33:in `watir'
         2: from /home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base/parts/webdriver.rb:64:in `selenium'
         1: from /home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base/parts/webdriver.rb:64:in `fail'
/home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base/parts/webdriver.rb:64:in `exception': Could not initialize Selenium. (SCNR::Engine::Browser::Engines::Error)
 [-] [/home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/ui/output_interface/implemented.rb#print_exception:16] [SCNR::Engine::Browser::Engines::Error] Could not initialize Selenium.                                               
 [-] [/home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base/parts/webdriver.rb:64:in `exception'
 [-] [/home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base/parts/webdriver.rb:64:in `fail'
 [-] [/home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base/parts/webdriver.rb:64:in `selenium'
 [-] [/home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base/parts/webdriver.rb:33:in `watir'
 [-] [/home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base/parts/webdriver.rb:94:in `start_webdriver'
 [-] [/home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base.rb:124:in `start'
 [-] [/home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base.rb:85:in `initialize'
 [-] [/home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/support/mixins/spec_instances.rb:64:in `initialize'
 [-] [/home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/parts/engine.rb:36:in `new'
 [-] [/home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/parts/engine.rb:36:in `initialize'
 [-] [/home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/parts/navigation.rb:39:in `initialize'
 [-] [/home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/parts/http.rb:38:in `initialize'
 [-] [/home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/parts/snapshots.rb:40:in `initialize'
 [-] [/home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser.rb:62:in `initialize'
 [-] [/home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/support/mixins/spec_instances.rb:64:in `initialize'
 [-] [/home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser_pool/worker.rb:56:in `initialize'
 [-] [/home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser_pool.rb:494:in `new'
 [-] [/home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser_pool.rb:494:in `block (2 levels) in initialize_workers'
 [-] [/home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/utilities.rb#exception_jail:400]                                                                                                                                            
 [-] [/home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/utilities.rb#exception_jail:401] Parent:                                                                                                                                    
 [-] [/home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/utilities.rb#exception_jail:402] SCNR::Engine::Framework                                                                                                                    
 [-] [/home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/utilities.rb#exception_jail:403]                                                                                                                                            
 [-] [/home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/utilities.rb#exception_jail:404] Block:                                                                                                                                     
 [-] [/home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/utilities.rb#exception_jail:405] #<Proc:0x0000000002565a20 /home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/framework.rb:96>
 [-] [/home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/utilities.rb#exception_jail:406]                                                                                                                                            
 [-] [/home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/utilities.rb#exception_jail:407] Caller:                                                                                                                                    
 [-] [/home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/utilities.rb#exception_jail:408] /home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/utilities.rb:395:in `exception_jail'
 [-] [/home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/utilities.rb#exception_jail:408] /home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/framework.rb:96:in `run'           
 [-] [/home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/utilities.rb#exception_jail:408] (eval):39:in `block (2 levels) in <encoded>'                                                                                               
 [-] [/home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/utilities.rb#exception_jail:408] /home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/dsel-0.1.0/lib/dsel/api/generator.rb:245:in `block (3 levels) in define_call_router'
 [-] [/home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/utilities.rb#exception_jail:408] /home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/dsel-0.1.0/lib/dsel/api/generator.rb:123:in `calling'                 
 [-] [/home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/utilities.rb#exception_jail:408] /home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/dsel-0.1.0/lib/dsel/api/generator.rb:266:in `method_missing'          
 [-] [/home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/utilities.rb#exception_jail:408] /home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/dsel-0.1.0/lib/dsel/api/generator.rb:244:in `block (2 levels) in define_call_router'
 [-] [/home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/utilities.rb#exception_jail:408] /home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-ui-cli-1.0dev/lib/scnr/ui/cli/engine.rb:135:in `block in run'    
 [-] [/home/kali/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/utilities.rb#exception_jail:409]

For the installation I used the script found on the site:
bash -c "$(curl -sSL https://get.ecsypno.com/scnr)"

I don't understand much about these things, I tried to do some research before writing this topic, but I couldn't find a solution.

**Comment by Zapotek** [comment]
Hello,

There's an issue when running from root.
Can you please try installing under a regular user account?

I'll add a check for this soon.

Cheers,
Tasos L.

**Comment by Mettthew** [comment]
Hi, I am using a kali linux virtual machine that I login to with my kali account information, I think I am performing all operations from an account and not root (also because when I need root privileges I am specified to use sudo).

But I am not very familiar with these things, so I could be wrong

**Comment by Zapotek** [comment]
You're right, I was going from a different issue. I find your issue
surprising.

I'll be looking into it.

**Comment by Mettthew** [comment]
Has the problem been solved?

**Comment by Zapotek** [comment]
Hello,

Can you try a different distro and let me know how it goes please?

Cheers

**Comment by Mettthew** [comment]
sfrotunately I don't have much space on my pc to try it in another distro, I tried re-downloading it but the problem unfortunately persists.

About a month or so ago I had already used it SCNR and it seemed to work properly on my virtual machine that I am using now, but since the ruby code expired, I tried to re-download it and it did not work as before

**Comment by Chengrongrong** [comment]
Before version is the working!! The new version is not working!

error message: Could not initialize Selenium. (SCNR::Engine::Browser::Engines::Error)

the problem to resolve?

**Comment by GhioRodolphe** [comment]
> Before version is the working!! The new version is not working!
> 
> error message: Could not initialize Selenium. (SCNR::Engine::Browser::Engines::Error)
> 
> the problem is resolve?

I've the same here:
```#<Thread:0x0000000001606ef8 /home/rghio/Tools/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser_pool.rb:493 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        14: from /home/rghio/Tools/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser_pool.rb:494:in `block (2 levels) in initialize_workers'
        13: from /home/rghio/Tools/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser_pool.rb:494:in `new'
        
[...]
        
/home/rghio/Tools/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base/parts/webdriver.rb:64:in `exception': Could not initialize Selenium. (SCNR::Engine::Browser::Engines::Error)
```

**Comment by Zapotek** [comment]
Did you by any chance ran SCNR from a root account first?

**Comment by Zapotek** [comment]
Should be fixed now.
Thanks for the feedback.
