### ISSUE TITLE
Scanning Application with WebSockets

### ISSUE THREAD

**Issue by Alucard23890** [scnr/installer#25]
Hi,
I want to scan an application which uses WebSockets to communicate with the Server. If I run SCNR against the application, it only checks the URLs found inside the Application itself but ignores WebSockets URLs. I can see in the Debug Logs that the Connection is established. I tried to use the same Domain for WebSocket and Application (with different ports) but they are still ignored.

Can SCNR even scan such applications and if yes, how?

**Comment by Zapotek** [comment]
Hello,

Yes it should be possible, I have an idea of what the issue might be though.

I'll examine it and get back to you ASAP.

Cheers

**Comment by Zapotek** [comment]
Hello,

Can you please provide me with the webapplication URL ( can be in private) in order to reproduce the issue?

Cheers

**Comment by Zapotek** [comment]
Hello,

I'm having some trouble setting up OWASP Damn Vulnerable Web Sockets, but some bugs have been fixed in SCNR that may help.
Can you give it a try please?

Cheers

**Comment by Zapotek** [comment]
Closing this as stale and requiring further feedback.
