### ISSUE TITLE
Cannot create XML reports from *.ser – SCNR::Engine

### ISSUE THREAD

**Issue by MrHr6874** [scnr/installer#32]
Hello,
I am using the tool to scan against OWASP Benchmark web application. I am running ./scnr against individual test cases. 
I am able to generate reports with ./scnr_reporter in Html and json format, however, I want my reports to be in xml format so that I can create benchmark scorecards for the tool. 

report.sh file contains 
`./scnr_reporter --report=xml:outfile=Benchmark.xml /home/test/.scnr/reports/Benchmark_LDAP_Injection.ser`

I am attaching the specific error below 
`bin su test report.sh
            Codename SCNR v1.0dev
    by Ecsypno Single Member P.C. (Copyright 2023)
             https://ecsypno.com

539:0: ERROR: Element 'url': 'https://localhost:8443/benchmark/ldapi-00/BenchmarkTest02472?username=scnr_engine_name&password=5543!%scnr_engine_secret&BenchmarkTest02472=Ms%20Bar%23%5E($!@$)(()))******' is not a valid value of the atomic type 'xs:anyURI'.
 -- Line 539, column 0, level 2.
----------------------------------------------------------------------------------------------------
530 | Content-Type: text/html;charset=utf-8&#xD;
531 | Content-Language: en&#xD;
532 | Content-Length: 3486&#xD;
533 | Date: Sat, 13 Jan 2024 06:45:26 GMT&#xD;
534 | Connection: close&#xD;
535 | &#xD;
536 | </raw_headers>
537 |         </response>
538 |         <dom>
539 |           <url>https://localhost:8443/benchmark/ldapi-00/BenchmarkTest02472?username=scnr_engine_name&amp;password=5543!%scnr_engine_secret&amp;BenchmarkTest02472=Ms%20Bar%23%5E($!@$)(()))******</url>
539 

 **[-] [/home/test/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/components/reporters/xml.rb#run:169] XML: Report could not be validated against the XSD due to the above errors.**`

I believe it has something to do with the <uri> paramater in the xml report format.

**Comment by Zapotek** [comment]
Hello,

Could you please send me the report via email at support@ecsypno.com ?

Cheers!

**Comment by MrHr6874** [comment]
Hello, what report should I send you exactly?
As I mentioned, I have not been able to generate the report via xml format.

**Comment by MrHr6874** [comment]
Hey,
I have sent the report created by scnr in **.ser** format

**Comment by MrHr6874** [comment]
Hello @Zapotek ,

Thanks a lot for you help!
The issue has been resolved.
You can close this issue now :)
