### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by Bzyczek7** [scnr/installer#35]
![image](https://github.com/scnr/installer/assets/157357274/c48a8561-49f6-4451-ab92-c378a2e67fb2)

2024-01-29 10:22:24 +0100 Listen loop: #<Errno::EMFILE: Too many open files - accept(2)>
"[NoMethodError] undefined method `my_symbolize_keys' for #<Exception:0x0000000003d5ecf8>"
2024-01-29 10:22:24 +0100 Listen loop: #<Errno::EMFILE: Too many open files - accept(2)>
[
    [ 0] "/home/marek/scnr-v1.1/.system/scnr-ui-pro/lib/scan_scheduler/helpers/scan.rb:268:in `block in update'",
    [ 1] "/home/marek/scnr-v1.1/.system/gems/gems/toq-0.0.4.1/lib/toq/client.rb:214:in `set_exception'",
    [ 2] "/home/marek/scnr-v1.1/.system/gems/gems/toq-0.0.4.1/lib/toq/client.rb:228:in `rescue in call_async'",
    [ 3] "/home/marek/scnr-v1.1/.system/gems/gems/toq-0.0.4.1/lib/toq/client.rb:220:in `call_async'",
    [ 4] "/home/marek/scnr-v1.1/.system/gems/gems/toq-0.0.4.1/lib/toq/client.rb:197:in `call'",
    [ 5] "/home/marek/scnr-v1.1/.system/gems/gems/toq-0.0.4.1/lib/toq/proxy.rb:72:in `forward'",
    [ 6] "/home/marek/scnr-v1.1/.system/gems/gems/toq-0.0.4.1/lib/toq/proxy.rb:79:in `method_missing'",
    [ 7] "/home/marek/scnr-v1.1/.system/scnr-ui-pro/lib/scan_scheduler/helpers/scan.rb:254:in `update'",
    [ 8] "/home/marek/scnr-v1.1/.system/scnr-ui-pro/lib/scan_scheduler/helpers/scan.rb:230:in `block in monitor'",
    [ 9] "/home/marek/scnr-v1.1/.system/gems/gems/raktr-0.0.3/lib/raktr/tasks/base.rb:51:in `call_task'",
    [10] "/home/marek/scnr-v1.1/.system/gems/gems/raktr-0.0.3/lib/raktr/tasks/persistent.rb:23:in `call'",
    [11] "/home/marek/scnr-v1.1/.system/gems/gems/raktr-0.0.3/lib/raktr/tasks/periodic.rb:42:in `call'",
    [12] "/home/marek/scnr-v1.1/.system/gems/gems/raktr-0.0.3/lib/raktr/tasks.rb:95:in `block in call'",
    [13] "/home/marek/scnr-v1.1/.system/gems/gems/raktr-0.0.3/lib/raktr/tasks.rb:95:in `each'",
    [14] "/home/marek/scnr-v1.1/.system/gems/gems/raktr-0.0.3/lib/raktr/tasks.rb:95:in `call'",
    [15] "/home/marek/scnr-v1.1/.system/gems/gems/raktr-0.0.3/lib/raktr.rb:305:in `block in run'",
    [16] "/home/marek/scnr-v1.1/.system/gems/gems/raktr-0.0.3/lib/raktr.rb:303:in `loop'",
    [17] "/home/marek/scnr-v1.1/.system/gems/gems/raktr-0.0.3/lib/raktr.rb:303:in `run'",
    [18] "/home/marek/scnr-v1.1/.system/gems/gems/raktr-0.0.3/lib/raktr.rb:345:in `block in run_in_thread'"
]
2024-01-29 10:22:24 +0100 Listen loop: #<Errno::EMFILE: Too many open files - accept(2)>
2024-01-29 10:22:25 +0100 Listen loop: #<Errno::EMFILE: Too many open files - accept(2)>
2024-01-29 10:22:25 +0100 Listen loop: #<Errno::EMFILE: Too many open files - accept(2)>
2024-01-29 10:22:25 +0100 Listen loop: #<Errno::EMFILE: Too many open files - accept(2)>
2024-01-29 10:22:25 +0100 Listen loop: #<Errno::EMFILE: Too many open files - accept(2)>
2024-01-29 10:22:25 +0100 Listen loop: #<Errno::EMFILE: Too many open files - accept(2)>

it goes into a loop in the log ... while i can't access through web-gui

**Comment by Bzyczek7** [comment]
2024-01-29 10:25:19 +0100 Listen loop: #<Errno::EMFILE: Too many open files - accept(2)>
"[NoMethodError] undefined method `my_symbolize_keys' for #<Exception:0x0000000003bed950>"
[
    [ 0] "/home/marek/scnr-v1.1/.system/scnr-ui-pro/lib/scan_scheduler/helpers/scan.rb:268:in `block in update'",
    [ 1] "/home/marek/scnr-v1.1/.system/gems/gems/toq-0.0.4.1/lib/toq/client.rb:214:in `set_exception'",
    [ 2] "/home/marek/scnr-v1.1/.system/gems/gems/toq-0.0.4.1/lib/toq/client.rb:228:in `rescue in call_async'",
    [ 3] "/home/marek/scnr-v1.1/.system/gems/gems/toq-0.0.4.1/lib/toq/client.rb:220:in `call_async'",
    [ 4] "/home/marek/scnr-v1.1/.system/gems/gems/toq-0.0.4.1/lib/toq/client.rb:197:in `call'",
    [ 5] "/home/marek/scnr-v1.1/.system/gems/gems/toq-0.0.4.1/lib/toq/proxy.rb:72:in `forward'",
    [ 6] "/home/marek/scnr-v1.1/.system/gems/gems/toq-0.0.4.1/lib/toq/proxy.rb:79:in `method_missing'",
    [ 7] "/home/marek/scnr-v1.1/.system/scnr-ui-pro/lib/scan_scheduler/helpers/scan.rb:254:in `update'",
    [ 8] "/home/marek/scnr-v1.1/.system/scnr-ui-pro/lib/scan_scheduler/helpers/scan.rb:230:in `block in monitor'",
    [ 9] "/home/marek/scnr-v1.1/.system/gems/gems/raktr-0.0.3/lib/raktr/tasks/base.rb:51:in `call_task'",
    [10] "/home/marek/scnr-v1.1/.system/gems/gems/raktr-0.0.3/lib/raktr/tasks/persistent.rb:23:in `call'",
    [11] "/home/marek/scnr-v1.1/.system/gems/gems/raktr-0.0.3/lib/raktr/tasks/periodic.rb:42:in `call'",
    [12] "/home/marek/scnr-v1.1/.system/gems/gems/raktr-0.0.3/lib/raktr/tasks.rb:95:in `block in call'",
    [13] "/home/marek/scnr-v1.1/.system/gems/gems/raktr-0.0.3/lib/raktr/tasks.rb:95:in `each'",
    [14] "/home/marek/scnr-v1.1/.system/gems/gems/raktr-0.0.3/lib/raktr/tasks.rb:95:in `call'",
    [15] "/home/marek/scnr-v1.1/.system/gems/gems/raktr-0.0.3/lib/raktr.rb:305:in `block in run'",
    [16] "/home/marek/scnr-v1.1/.system/gems/gems/raktr-0.0.3/lib/raktr.rb:303:in `loop'",
    [17] "/home/marek/scnr-v1.1/.system/gems/gems/raktr-0.0.3/lib/raktr.rb:303:in `run'",
    [18] "/home/marek/scnr-v1.1/.system/gems/gems/raktr-0.0.3/lib/raktr.rb:345:in `block in run_in_thread'"
]
2024-01-29 10:25:20 +0100 Listen loop: #<Errno::EMFILE: Too many open files - accept(2)>

**Comment by Zapotek** [comment]
Hello,

Are you running multiple scans in parallel?
If so, how many?

**Comment by Bzyczek7** [comment]
I restarted, and now i get this 

Traceback (most recent call last):
	16: from (eval):5:in `block (2 levels) in <encoded>'
	15: from /home/marek/scnr-v1.1/.system/gems/gems/scnr-engine-0.1/lib/scnr/engine/framework/parts/state.rb:105:in `clean_up'
	14: from /home/marek/scnr-v1.1/.system/gems/gems/scnr-engine-0.1/lib/scnr/engine/framework/parts/browser.rb:116:in `shutdown_browser_pool'
	13: from /home/marek/scnr-v1.1/.system/gems/gems/scnr-engine-0.1/lib/scnr/engine/browser_pool.rb:321:in `shutdown'
	12: from /home/marek/scnr-v1.1/.system/gems/gems/scnr-engine-0.1/lib/scnr/engine/support/database/categorized_queue.rb:170:in `clear'
	11: from /home/marek/scnr-v1.1/.system/gems/gems/scnr-engine-0.1/lib/scnr/engine/support/database/categorized_queue.rb:197:in `synchronize'
	10: from /home/marek/scnr-v1.1/.system/gems/gems/scnr-engine-0.1/lib/scnr/engine/support/database/categorized_queue.rb:197:in `synchronize'
	 9: from /home/marek/scnr-v1.1/.system/gems/gems/scnr-engine-0.1/lib/scnr/engine/support/database/categorized_queue.rb:171:in `block in clear'
	 8: from /home/marek/scnr-v1.1/.system/gems/gems/scnr-engine-0.1/lib/scnr/engine/support/database/categorized_queue.rb:171:in `each'
	 7: from /home/marek/scnr-v1.1/.system/gems/gems/scnr-engine-0.1/lib/scnr/engine/support/database/categorized_queue.rb:177:in `block (2 levels) in clear'
	 6: from /home/marek/scnr-v1.1/.system/gems/gems/scnr-engine-0.1/lib/scnr/engine/support/database/base.rb:148:in `delete_file'
	 5: from /home/marek/scnr-v1.1/.system/gems/gems/scnr-engine-0.1/lib/scnr/engine/support/database/base.rb:36:in `decrement_disk_space'
	 4: from /home/marek/scnr-v1.1/.system/gems/gems/scnr-engine-0.1/lib/scnr/engine/support/database/base.rb:70:in `set_disk_space'
	 3: from /home/marek/scnr-v1.1/.system/gems/gems/scnr-engine-0.1/lib/scnr/engine/support/database/base.rb:77:in `synchronize'
	 2: from /home/marek/scnr-v1.1/.system/gems/gems/scnr-engine-0.1/lib/scnr/engine/support/database/base.rb:77:in `synchronize'
	 1: from /home/marek/scnr-v1.1/.system/gems/gems/scnr-engine-0.1/lib/scnr/engine/support/database/base.rb:72:in `block in set_disk_space'
/home/marek/scnr-v1.1/.system/gems/gems/scnr-engine-0.1/lib/scnr/engine/support/database/base.rb:72:in `write': Too many open files @ rb_sysopen - /tmp/SCNR_Engine_24061/Database_disk_space (Errno::EMFILE)
Traceback (most recent call last):
	16: from (eval):5:in `block (2 levels) in <encoded>'
	15: from /home/marek/scnr-v1.1/.system/gems/gems/scnr-engine-0.1/lib/scnr/engine/framework/parts/state.rb:105:in `clean_up'
	14: from /home/marek/scnr-v1.1/.system/gems/gems/scnr-engine-0.1/lib/scnr/engine/framework/parts/browser.rb:116:in `shutdown_browser_pool'
	13: from /home/marek/scnr-v1.1/.system/gems/gems/scnr-engine-0.1/lib/scnr/engine/browser_pool.rb:321:in `shutdown'
	12: from /home/marek/scnr-v1.1/.system/gems/gems/scnr-engine-0.1/lib/scnr/engine/support/database/categorized_queue.rb:170:in `clear'
	11: from /home/marek/scnr-v1.1/.system/gems/gems/scnr-engine-0.1/lib/scnr/engine/support/database/categorized_queue.rb:197:in `synchronize'
	10: from /home/marek/scnr-v1.1/.system/gems/gems/scnr-engine-0.1/lib/scnr/engine/support/database/categorized_queue.rb:197:in `synchronize'
	 9: from /home/marek/scnr-v1.1/.system/gems/gems/scnr-engine-0.1/lib/scnr/engine/support/database/categorized_queue.rb:171:in `block in clear'
	 8: from /home/marek/scnr-v1.1/.system/gems/gems/scnr-engine-0.1/lib/scnr/engine/support/database/categorized_queue.rb:171:in `each'
	 7: from /home/marek/scnr-v1.1/.system/gems/gems/scnr-engine-0.1/lib/scnr/engine/support/database/categorized_queue.rb:177:in `block (2 levels) in clear'
	 6: from /home/marek/scnr-v1.1/.system/gems/gems/scnr-engine-0.1/lib/scnr/engine/support/database/base.rb:148:in `delete_file'
	 5: from /home/marek/scnr-v1.1/.system/gems/gems/scnr-engine-0.1/lib/scnr/engine/support/database/base.rb:36:in `decrement_disk_space'
	 4: from /home/marek/scnr-v1.1/.system/gems/gems/scnr-engine-0.1/lib/scnr/engine/support/database/base.rb:70:in `set_disk_space'
	 3: from /home/marek/scnr-v1.1/.system/gems/gems/scnr-engine-0.1/lib/scnr/engine/support/database/base.rb:77:in `synchronize'
	 2: from /home/marek/scnr-v1.1/.system/gems/gems/scnr-engine-0.1/lib/scnr/engine/support/database/base.rb:77:in `synchronize'
	 1: from /home/marek/scnr-v1.1/.system/gems/gems/scnr-engine-0.1/lib/scnr/engine/support/database/base.rb:72:in `block in set_disk_space'
/home/marek/scnr-v1.1/.system/gems/gems/scnr-engine-0.1/lib/scnr/engine/support/database/base.rb:72:in `write': Too many open files @ rb_sysopen - /tmp/SCNR_Engine_24061/Database_disk_space (Errno::EMFILE)
	13: from /home/marek/scnr-v1.1/.system/gems/gems/scnr-engine-0.1/lib/scnr/engine/support/database/base.rb:94:in `block in initialize'
	12: from /home/marek/scnr-v1.1/.system/gems/gems/scnr-engine-0.1/lib/scnr/engine/support/database/categorized_queue.rb:170:in `clear'
	11: from /home/marek/scnr-v1.1/.system/gems/gems/scnr-engine-0.1/lib/scnr/engine/support/database/categorized_queue.rb:197:in `synchronize'
	10: from /home/marek/scnr-v1.1/.system/gems/gems/scnr-engine-0.1/lib/scnr/engine/support/database/categorized_queue.rb:197:in `synchronize'
	 9: from /home/marek/scnr-v1.1/.system/gems/gems/scnr-engine-0.1/lib/scnr/engine/support/database/categorized_queue.rb:171:in `block in clear'
	 8: from /home/marek/scnr-v1.1/.system/gems/gems/scnr-engine-0.1/lib/scnr/engine/support/database/categorized_queue.rb:171:in `each'
	 7: from /home/marek/scnr-v1.1/.system/gems/gems/scnr-engine-0.1/lib/scnr/engine/support/database/categorized_queue.rb:177:in `block (2 levels) in clear'
	 6: from /home/marek/scnr-v1.1/.system/gems/gems/scnr-engine-0.1/lib/scnr/engine/support/database/base.rb:148:in `delete_file'
	 5: from /home/marek/scnr-v1.1/.system/gems/gems/scnr-engine-0.1/lib/scnr/engine/support/database/base.rb:36:in `decrement_disk_space'
	 4: from /home/marek/scnr-v1.1/.system/gems/gems/scnr-engine-0.1/lib/scnr/engine/support/database/base.rb:70:in `set_disk_space'
	 3: from /home/marek/scnr-v1.1/.system/gems/gems/scnr-engine-0.1/lib/scnr/engine/support/database/base.rb:77:in `synchronize'
	 2: from /home/marek/scnr-v1.1/.system/gems/gems/scnr-engine-0.1/lib/scnr/engine/support/database/base.rb:77:in `synchronize'
	 1: from /home/marek/scnr-v1.1/.system/gems/gems/scnr-engine-0.1/lib/scnr/engine/support/database/base.rb:72:in `block in set_disk_space'
/home/marek/scnr-v1.1/.system/gems/gems/scnr-engine-0.1/lib/scnr/engine/support/database/base.rb:72:in `write': Too many open files @ rb_sysopen - /tmp/SCNR_Engine_24061/Database_disk_space (Errno::EMFILE)

**Comment by Bzyczek7** [comment]
nope, just had one running.

**Comment by Bzyczek7** [comment]
with the default settings.

**Comment by Zapotek** [comment]
Can you please show me the output of:
`ulimit -n`

**Comment by Bzyczek7** [comment]
sure ... here it is ... 

/scnr-v1.1$ ulimit -n
1024

**Comment by Bzyczek7** [comment]
i have default ubuntu 
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"

**Comment by Zapotek** [comment]
Try increasing the limit with: `ulimit -n 6500`

**Comment by Bzyczek7** [comment]
k will do, and i'll rescan

**Comment by Bzyczek7** [comment]
Quick question, will rescan continue where the previous failed or will re-do ? Because last time it took 166 hours before it failed.

**Comment by Zapotek** [comment]
Also fixed the exception handling for this.

**Comment by Bzyczek7** [comment]
what do you need me to do?

**Comment by Bzyczek7** [comment]
I'm running it because it doesn't cost me anything ... Let's see what happens this time ... It's still running since Monday.

**Comment by Zapotek** [comment]
Cool, how much RAM does the machine have?

**Comment by Zapotek** [comment]
New release is up, it will require [activation](https://ecsypno.com/products/scnr).

**Comment by Bzyczek7** [comment]
it failed again unfortunately ... this time it froze my Laptop completely.

Intel® Core™ i5-1035G1 CPU @ 1.00GHz × 8
16,0 GiB RAM

**Comment by Bzyczek7** [comment]
FYI

marek@marek-HP-Laptop-17-by3xxx:~/scnr-v1.1/bin$ ./scnr-v1.3.1/bin/scnr_pro
curl: (6) Could not resolve host: raw.githubusercontent.com
 -- Could not check for update.

**Comment by Bzyczek7** [comment]
got the new version installed and the SQL configured to Postgre

I'll run the same scan again to see if anything changes ... will keep you posted. It will take a while.

**Comment by Zapotek** [comment]
Can you try using the CLI?
There could be a file descriptor leak somewhere and I'd like to rule out the engine.

**Comment by Bzyczek7** [comment]
ok let me see how it can be done.

**Comment by Bzyczek7** [comment]
is there a howto ?

**Comment by Zapotek** [comment]
Just `bin/scnr URL`

**Comment by Bzyczek7** [comment]
still scanning :( although long, it still has not crashed.

**Comment by Bzyczek7** [comment]
I'm doing the scan_pro have not executed the CLI yet ... i want this to finish.

**Comment by Bzyczek7** [comment]
it seems the scan is a lot slower now ... it's 212 hours and i'm not even at the part where the other stopped ... the others stopped at around 12000 pages .... this one is at 8400 so far ... just fyi

**Comment by Zapotek** [comment]
Thanks for the info.
I didn't do anything to cause that, must be env issues.

**Comment by Bzyczek7** [comment]
failed :( at about the same amout of pages 
![image](https://github.com/scnr/installer/assets/157357274/bc3871eb-c0cd-4c94-934d-f625dc88b0c1)

**Comment by Bzyczek7** [comment]
[ 0] "/home/marek/scnr-v1.3.1/.system/scnr-ui-pro/lib/scan_scheduler/helpers/instance.rb:82:in `instance_for'",
    [ 1] "/home/marek/scnr-v1.3.1/.system/scnr-ui-pro/lib/scan_scheduler/helpers/scan.rb:244:in `update'",
    [ 2] "/home/marek/scnr-v1.3.1/.system/scnr-ui-pro/lib/scan_scheduler/helpers/scan.rb:230:in `block in monitor'",
    [ 3] "/home/marek/scnr-v1.3.1/.system/gems/gems/raktr-0.0.3/lib/raktr/tasks/base.rb:51:in `call_task'",
    [ 4] "/home/marek/scnr-v1.3.1/.system/gems/gems/raktr-0.0.3/lib/raktr/tasks/persistent.rb:23:in `call'",
    [ 5] "/home/marek/scnr-v1.3.1/.system/gems/gems/raktr-0.0.3/lib/raktr/tasks/periodic.rb:42:in `call'",
    [ 6] "/home/marek/scnr-v1.3.1/.system/gems/gems/raktr-0.0.3/lib/raktr/tasks.rb:95:in `block in call'",
    [ 7] "/home/marek/scnr-v1.3.1/.system/gems/gems/raktr-0.0.3/lib/raktr/tasks.rb:95:in `each'",
    [ 8] "/home/marek/scnr-v1.3.1/.system/gems/gems/raktr-0.0.3/lib/raktr/tasks.rb:95:in `call'",
    [ 9] "/home/marek/scnr-v1.3.1/.system/gems/gems/raktr-0.0.3/lib/raktr.rb:305:in `block in run'",
    [10] "/home/marek/scnr-v1.3.1/.system/gems/gems/raktr-0.0.3/lib/raktr.rb:303:in `loop'",
    [11] "/home/marek/scnr-v1.3.1/.system/gems/gems/raktr-0.0.3/lib/raktr.rb:303:in `run'",
    [12] "/home/marek/scnr-v1.3.1/.system/gems/gems/raktr-0.0.3/lib/raktr.rb:345:in `block in run_in_thread'"
]
"[ScanScheduler::Helpers::Instance::Error::InstanceNotFound] [ScanScheduler#237456] [3rd wentylacja] Instance not found."

**Comment by Bzyczek7** [comment]
doing the cli scan ... i'm still using 1.3.1 and have not upgraded

**Comment by Bzyczek7** [comment]
Wow I don't know how long it has been it is still scanning ...

**Comment by Bzyczek7** [comment]
amazing, it is still running ...

**Comment by Zapotek** [comment]
Haha how big is that site?

**Comment by Bzyczek7** [comment]
In my opinion it's not a big store ... I picked one of our smaller one's ... I wonder how it would do on our main site ... I wouldn't live to see the end :P

**Comment by Zapotek** [comment]
Is there any functionality that would generate a large/infinite amount of
pages?

Like a calendar for example?

**Comment by Bzyczek7** [comment]
I noticed there are forums on it ...

**Comment by Zapotek** [comment]
That would explain it.
You may want to keep an eye out for redundant pages and add some rules for
them.

Check out the scope options.

**Comment by Zapotek** [comment]
CLI:

```
      --scope-redundant-path-pattern PATTERN:LIMIT
                              Limit crawl on redundant pages like galleries or catalogs.
                                URLs matching PATTERN will be crawled LIMIT amount of times.
                                Can be used multiple times.
                               
      --scope-auto-redundant [LIMIT]
                              Only follow URLs with identical query parameter names LIMIT amount of times.
                                (Default: 10)
```

WebUI: Visit the site settings page and look for the "Scope" section on the  left-hand sidebar.

Also see: https://documentation.ecsypno.com/scnr/how-to/optimize-scans.html#dont-follow-redundant-pages

**Comment by Bzyczek7** [comment]
Unfortunately i had to stop the scan ... but now my license expired so oh well ... can't redo the scan with the options you suggested.

**Comment by Zapotek** [comment]
You can use the Community edition.
