### ISSUE TITLE
License Activation Fails

### ISSUE THREAD

**Issue by cclements** [scnr/installer#36]
scnr-v1.3/bin/scnr_activate ********************
[ERROR] Could not validate license key with server (remote_file_not_found).

**Comment by Zapotek** [comment]
Hello,

What distro are you using?

Cheers

**Comment by cclements** [comment]
Hey Tasos, longtime former Arachni user.  I'm running the latest Kali x64 on WSL2.
________________________________

**Comment by Zapotek** [comment]
Thanks.

From what I can tell so far it's a certificate issue, looking into it.

Cheers!

**Comment by Zapotek** [comment]
Just pushed v1.3.1 with a fix, should work now.
Please give it a try and let me know.

Cheers!
