### ISSUE TITLE
Need help in setting up codenamescnr

### ISSUE THREAD

**Issue by jyotibora-sap** [scnr/installer#38]
1) I got the trial version with the Activated Key.
Yesterday I have installed it on my machine successfully. (I have installed Ubuntu on Windows 11 and then installed codenameSCNR)
i have tried running scanning as well, but it failed.
Now today I have restarted my system. So to start Codenamescnr again do I need to install it again? After doing so i am getting below error : 

![image](https://github.com/scnr/installer/assets/110669095/9df94333-9dcb-4648-8fcf-b7a3d971f354)

Can you please help me in that i am trying to use CLI.

2) for trial version, can i use WEB scanner ?
Kindly please confirm for the same

**Comment by Zapotek** [comment]
You don't need to install it again, you're outside of the directory with the bin folder.

Maybe first try `cd scnr-*`?

**Comment by jyotibora-sap** [comment]
I have tried but not working

**Comment by Zapotek** [comment]
When running the command from inside the scnr directory like I described
what is the output?

**Comment by jyotibora-sap** [comment]
Hey I found the directory!
tried running bin/scnr "https://psinnersource.stg.pscloudhub.com/" getting below error.Attach is the report 
est@WKWZTxgIa9dtWBV:~/scnr-v1.3.5$ bin/scnr "https://psinnersource.stg.pscloudhub.com/"
            Codename SCNR v1.3.5
    by Ecsypno Single Member P.C. (Copyright 2023)
             https://ecsypno.com


 [~] No checks were specified, loading all.
 [~] No element audit options were specified, will audit links, forms, cookies, headers, UI inputs, UI forms, JSONs and XMLs.

 [*] Initializing...
 [*] Preparing plugins...
 [*] ... done.
 [*] BrowserPool: Initializing 4 Chrome browsers...
/home/test/scnr-v1.3.5/bin/../.system/usr/../opt/chrome-linux/chrome.original: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
/home/test/scnr-v1.3.5/bin/../.system/usr/bin/chromedriver: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
#<Thread:0x0000000003792e78 /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser_pool.rb:497 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        13: from /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser_pool.rb:498:in `block (2 levels) in initialize_workers'
        12: from /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser_pool.rb:498:in `new'        11: from /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser_pool/worker.rb:56:in `initialize'
        10: from /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/support/mixins/spec_instances.rb:64:in `initialize'
         9: from /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser.rb:62:in `initialize'
         8: from /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser/parts/engine.rb:36:in `initialize'
         7: from /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser/parts/engine.rb:36:in `new'
         6: from /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/support/mixins/spec_instances.rb:64:in `initialize'
         5: from /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser/engines/base.rb:83:in `initialize'
         4: from /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser/engines/base.rb:128:in `ensure_version_compatibility'
         3: from /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser/engines/base.rb:128:in `each'
         2: from /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser/engines/base.rb:134:in `block in ensure_version_compatibility'
         1: from /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser/engines/base.rb:134:in `fail'
/home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser/engines/base.rb:134:in `exception': chrome version is 0 but needs to be between 97 and 1000. (SCNR::Engine::Browser::Engines::Error::IncompatibleVersion)
#<Thread:0x0000000003792a90 /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser_pool.rb:497 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        13: from /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser_pool.rb:498:in `block (2 levels) in initialize_workers'
        12: from /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser_pool.rb:498:in `new'        11: from /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser_pool/worker.rb:56:in `initialize'
        10: from /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/support/mixins/spec_instances.rb:64:in `initialize'
         9: from /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser.rb:62:in `initialize'
         8: from /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser/parts/engine.rb:36:in `initialize'
         7: from /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser/parts/engine.rb:36:in `new'
         6: from /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/support/mixins/spec_instances.rb:64:in `initialize'
         5: from /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser/engines/base.rb:83:in `initialize'
         4: from /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser/engines/base.rb:128:in `ensure_version_compatibility'
         3: from /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser/engines/base.rb:128:in `each'
         2: from /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser/engines/base.rb:134:in `block in ensure_version_compatibility'
         1: from /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser/engines/base.rb:134:in `fail'
/home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser/engines/base.rb:134:in `exception': chrome version is 0 but needs to be between 97 and 1000. (SCNR::Engine::Browser::Engines::Error::IncompatibleVersion)
#<Thread:0x0000000003792c98 /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser_pool.rb:497 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        13: from /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser_pool.rb:498:in `block (2 levels) in initialize_workers'
        12: from /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser_pool.rb:498:in `new'        11: from /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser_pool/worker.rb:56:in `initialize'
        10: from /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/support/mixins/spec_instances.rb:64:in `initialize'
         9: from /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser.rb:62:in `initialize'
         8: from /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser/parts/engine.rb:36:in `initialize'
         7: from /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser/parts/engine.rb:36:in `new'
         6: from /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/support/mixins/spec_instances.rb:64:in `initialize'
         5: from /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser/engines/base.rb:83:in `initialize'
         4: from /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser/engines/base.rb:128:in `ensure_version_compatibility'
         3: from /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser/engines/base.rb:128:in `each'
         2: from /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser/engines/base.rb:134:in `block in ensure_version_compatibility'
         1: from /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser/engines/base.rb:134:in `fail'
/home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser/engines/base.rb:134:in `exception': chrome version is 0 but needs to be between 97 and 1000. (SCNR::Engine::Browser::Engines::Error::IncompatibleVersion)
#<Thread:0x0000000003793148 /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser_pool.rb:497 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        13: from /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser_pool.rb:498:in `block (2 levels) in initialize_workers'
        12: from /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser_pool.rb:498:in `new'        11: from /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser_pool/worker.rb:56:in `initialize'
        10: from /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/support/mixins/spec_instances.rb:64:in `initialize'
         9: from /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser.rb:62:in `initialize'
         8: from /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser/parts/engine.rb:36:in `initialize'
         7: from /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser/parts/engine.rb:36:in `new'
         6: from /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/support/mixins/spec_instances.rb:64:in `initialize'
         5: from /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser/engines/base.rb:83:in `initialize'
         4: from /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser/engines/base.rb:128:in `ensure_version_compatibility'
         3: from /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser/engines/base.rb:128:in `each'
         2: from /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser/engines/base.rb:134:in `block in ensure_version_compatibility'
         1: from /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser/engines/base.rb:134:in `fail'
/home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser/engines/base.rb:134:in `exception': chrome version is 0 but needs to be between 97 and 1000. (SCNR::Engine::Browser::Engines::Error::IncompatibleVersion)
 [-] [/home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/ui/output_interface/implemented.rb#print_exception:16] [SCNR::Engine::Browser::Engines::Error::IncompatibleVersion] chrome version is 0 but needs to be between 97 and 1000.
 [-] [/home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser/engines/base.rb:134:in `exception'
 [-] [/home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser/engines/base.rb:134:in `fail'
 [-] [/home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser/engines/base.rb:134:in `block in ensure_version_compatibility'
 [-] [/home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser/engines/base.rb:128:in `each'
 [-] [/home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser/engines/base.rb:128:in `ensure_version_compatibility'
 [-] [/home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser/engines/base.rb:83:in `initialize'
 [-] [/home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/support/mixins/spec_instances.rb:64:in `initialize'
 [-] [/home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser/parts/engine.rb:36:in `new'
 [-] [/home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser/parts/engine.rb:36:in `initialize'
 [-] [/home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser.rb:62:in `initialize'
 [-] [/home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/support/mixins/spec_instances.rb:64:in `initialize'
 [-] [/home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser_pool/worker.rb:56:in `initialize'
 [-] [/home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser_pool.rb:498:in `new'
 [-] [/home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/browser_pool.rb:498:in `block (2 levels) in initialize_workers'
 [-] [/home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/utilities.rb#exception_jail:400]
 [-] [/home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/utilities.rb#exception_jail:401] Parent:
 [-] [/home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/utilities.rb#exception_jail:402] SCNR::Engine::Framework
 [-] [/home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/utilities.rb#exception_jail:403]
 [-] [/home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/utilities.rb#exception_jail:404] Block: [-] [/home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/utilities.rb#exception_jail:405] #<Proc:0x00000000045f7108 /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/framework.rb:96>
 [-] [/home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/utilities.rb#exception_jail:406]
 [-] [/home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/utilities.rb#exception_jail:407] Caller:
 [-] [/home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/utilities.rb#exception_jail:408] /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/utilities.rb:395:in `exception_jail'
 [-] [/home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/utilities.rb#exception_jail:408] /home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/framework.rb:96:in `run'
 [-] [/home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/utilities.rb#exception_jail:408] (eval):39:in `block (2 levels) in <encoded>'
 [-] [/home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/utilities.rb#exception_jail:408] /home/test/scnr-v1.3.5/.system/gems/gems/dsel-0.1.0/lib/dsel/api/generator.rb:245:in `block (3 levels) in define_call_router'
 [-] [/home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/utilities.rb#exception_jail:408] /home/test/scnr-v1.3.5/.system/gems/gems/dsel-0.1.0/lib/dsel/api/generator.rb:123:in `calling'
 [-] [/home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/utilities.rb#exception_jail:408] /home/test/scnr-v1.3.5/.system/gems/gems/dsel-0.1.0/lib/dsel/api/generator.rb:266:in `method_missing'
 [-] [/home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/utilities.rb#exception_jail:408] /home/test/scnr-v1.3.5/.system/gems/gems/dsel-0.1.0/lib/dsel/api/generator.rb:244:in `block (2 levels) in define_call_router'
 [-] [/home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/utilities.rb#exception_jail:408] /home/test/scnr-v1.3.5/.system/gems/gems/scnr-ui-cli-0.1.2/lib/scnr/ui/cli/engine.rb:135:in `run'
 [-] [/home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/utilities.rb#exception_jail:408] /home/test/scnr-v1.3.5/.system/gems/gems/scnr-ui-cli-0.1.2/lib/scnr/ui/cli/engine.rb:111:in `initialize'
 [-] [/home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/utilities.rb#exception_jail:408] /home/test/scnr-v1.3.5/.system/gems/gems/scnr-ui-cli-0.1.2/bin/scnr.rb:12:in `new'
 [-] [/home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/utilities.rb#exception_jail:408] /home/test/scnr-v1.3.5/.system/gems/gems/scnr-ui-cli-0.1.2/bin/scnr.rb:12:in `<encoded>'
 [-] [/home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/utilities.rb#exception_jail:408] /home/test/scnr-v1.3.5/.system/gems/gems/scnr-ui-cli-0.1.2/bin/scnr.rb:3:in `RGLoader_load'
 [-] [/home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/utilities.rb#exception_jail:408] /home/test/scnr-v1.3.5/.system/gems/gems/scnr-ui-cli-0.1.2/bin/scnr.rb:3:in `<top (required)>'
 [-] [/home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/utilities.rb#exception_jail:408] /home/test/scnr-v1.3.5/bin/../.system/gems/bin/scnr.rb:25:in `load'
 [-] [/home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/utilities.rb#exception_jail:408] /home/test/scnr-v1.3.5/bin/../.system/gems/bin/scnr.rb:25:in `<main>'
 [-] [/home/test/scnr-v1.3.5/.system/gems/gems/scnr-engine-0.1.2/lib/scnr/engine/utilities.rb#exception_jail:409] --------------------------------------------------------------------------------


================================================================================


 [+] Web Application Security Report - SCNR::Engine Framework

 [~] Report generated on: 2024-02-27 17:23:53 +0530

 [+] System settings:
 [~] ---------------
 [~] Version:           0.1.2
 [~] Seed:              b033d119a46f770f9b916f7640e2876b
 [~] Audit started on:  2024-02-27 17:23:53 +0530
 [~] Audit finished on: 2024-02-27 17:23:53 +0530
 [~] Runtime:           00:00:00

 [~] URL:        https://psinnersource.stg.pscloudhub.com/
 [~] User agent:

 [*] Audited elements:
 [~] * Links
 [~] * Forms
 [~] * Cookies
 [~] * Headers
 [~] * XMLs
 [~] * JSONs
 [~] * UI inputs
 [~] * UI forms

 [*] Checks: *

 [~] ===========================

 [+] 0 issues were detected.


 [~] Report saved at: /home/test/.scnr/reports/psinnersource.stg.pscloudhub.com_2024-02-27_17_23_53_+0530.ser [0.0MB]
 [~] The scan has logged errors: /home/test/scnr-v1.3.5/bin/../.system/../logs/engine/error-843.log



 [~] Audited 0 page snapshots.

 [~] Duration: 00:00:00
 [~] Processed 0/0 HTTP requests -- failed: 0
 [~] -- 0.0 requests/second.
 [~] Processed 0/0 browser jobs -- failed: 0
 [~] -- 0 second/job.

 [~] Burst avg application time  0.0 seconds
 [~] Burst average response time 0.0 seconds
 [~] Burst average responses/s   0.0 responses/second

 [~] Average application time    0.0 seconds
 [~] Download speed              0.0 KBps
 [~] Upload speed                0.0 KBps
 [~] Concurrency                 10/10 connections

====================================================
 [~] Please provide feedback at: contact@ecsypno.com
 [~] -- Thank you in advance!

**Comment by Zapotek** [comment]
Ah OK, that's helpful, thank you.

Please try:
`sudo apt install libgconf-2-4 libatk1.0-0 libatk-bridge2.0-0 libgdk-pixbuf2.0-0 libgtk-3-0 libgbm-dev libnss3-dev libxss-dev `

And then try launching Codename SCNR again.

**Comment by Zapotek** [comment]
See: https://github.com/scnr/installer?tab=readme-ov-file#dependencies-for-headlessminimal-environments

**Comment by jyotibora-sap** [comment]
I have run these commands . It ran successfully.  but I have noticed that the license is getting expired withing 1 day.
I have been using the same machine test@WKWZTxgIa9dtWBV.Please see the attached image for this.

<img width="602" alt="errorscnr" src="https://github.com/scnr/installer/assets/110669095/abfd3325-a6cf-4740-b28a-81ace6be9113">

**Comment by Zapotek** [comment]
No it hasn't expired but the MAC address of the first network interface must have changed. That's what the license binds to.

I'll look into it from my side to try and find the appropriate setting for WSL but in the meantime please talk to your administrator, they will be able to help.

**Comment by Zapotek** [comment]
After some research, I decided not to support WSL as it doesn't let you maintain the same MAC address as is required by Codename SCNR's licensing system.
The installer has been updated accordingly.

There are some hacks available but I'd rather not expect the user to go through that ordeal, and simply use VirtualBox instead.

Sorry for the bad news.

**Comment by jyotibora-sap** [comment]
Thanks much for the support! Much appreciated

**Comment by Zapotek** [comment]
Due to a change needed for another situation, Codename SCNR now supports WSL. 😁

v1.3.8.1 is up and should work fine after installing the dependencies mentioned in a previous comment.

Let me know if you come across any issues.
