### ISSUE TITLE
how can I use login_script in CLI command

### ISSUE THREAD

**Issue by souplim** [scnr/installer#39]
Hello

Web ui isn't working for me, so maybe I can't help but using CLI.
I want to use login_script for scanning my web site.
However I couldn't find full login_script I guess.

```
response = http.post( 'http://testfire.net/bank/login.aspx',
    parameters:     {
        'uid'   => 'jsmith',
        'passw' => 'Demo1234'
    },
    mode:           :sync,
    update_cookies: true
)

SCNR::Engine::Options.session.check_url     = to_absolute( response.headers.location, response.url )
SCNR::Engine::Options.session.check_pattern = /Sign Off|MY ACCOUNT/
```
Because when I just paste this code, error message goes like 
<NameError: undefined local variable or method 'http' for main:Object>

I tried to find login_script.rb in the package I downloaded, but I couldn't.

Thank you in advance!

**Comment by Zapotek** [comment]
Hello,

Where did you paste this code?
Did you try to run it as a standalone Ruby script?

It's meant to be run via either the `login_script` plugin or the WebUI login configuration.


Cheers

**Comment by souplim** [comment]
here is my command

```
./scnr https://mysite --system-slots-override --checks=- --script=/home/user/scnr-v1.5.1/.system/glems/gemms/scnr-engin-0.1.2/components/plugins/login/login_script.rb --scope-exclude-patterhn=logout
```

and I pasted that code to login_script.rb

Thank you for your help!

**Comment by Zapotek** [comment]
Hello,

That's not how the `login_script` plugin works, it goes like:

`--plugin=login_script:script=my_login_script.rb`

What you're using is for generic scripts to help/configure the scan.

Cheers!
