### ISSUE TITLE
in `final': bad decrypt (OpenSSL::Cipher::CipherError)

### ISSUE THREAD

**Issue by sanholy** [scnr/installer#40]
bundler: failed to load command: rackup (/opt/dast/scnr-v1.5.1/.system/gems/bin/rackup)
Traceback (most recent call last):
        40: from /opt/dast/scnr-v1.5.1/bin/../.system/gems/bin/bundle:25:in `<main>'
        39: from /opt/dast/scnr-v1.5.1/bin/../.system/gems/bin/bundle:25:in `load'
        38: from /opt/dast/scnr-v1.5.1/.system/gems/gems/bundler-2.4.22/exe/bundle:29:in `<top (required)>'
        37: from /opt/dast/scnr-v1.5.1/.system/gems/gems/bundler-2.4.22/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        36: from /opt/dast/scnr-v1.5.1/.system/gems/gems/bundler-2.4.22/exe/bundle:37:in `block in <top (required)>'
        35: from /opt/dast/scnr-v1.5.1/.system/gems/gems/bundler-2.4.22/lib/bundler/cli.rb:28:in `start'
        34: from /opt/dast/scnr-v1.5.1/.system/gems/gems/bundler-2.4.22/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
        33: from /opt/dast/scnr-v1.5.1/.system/gems/gems/bundler-2.4.22/lib/bundler/cli.rb:34:in `dispatch'
        32: from /opt/dast/scnr-v1.5.1/.system/gems/gems/bundler-2.4.22/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
        31: from /opt/dast/scnr-v1.5.1/.system/gems/gems/bundler-2.4.22/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        30: from /opt/dast/scnr-v1.5.1/.system/gems/gems/bundler-2.4.22/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
        29: from /opt/dast/scnr-v1.5.1/.system/gems/gems/bundler-2.4.22/lib/bundler/cli.rb:492:in `exec'
        28: from /opt/dast/scnr-v1.5.1/.system/gems/gems/bundler-2.4.22/lib/bundler/cli/exec.rb:23:in `run'
        27: from /opt/dast/scnr-v1.5.1/.system/gems/gems/bundler-2.4.22/lib/bundler/cli/exec.rb:58:in `kernel_load'
        26: from /opt/dast/scnr-v1.5.1/.system/gems/gems/bundler-2.4.22/lib/bundler/cli/exec.rb:58:in `load'
        25: from /opt/dast/scnr-v1.5.1/.system/gems/bin/rackup:25:in `<top (required)>'
        24: from /opt/dast/scnr-v1.5.1/.system/gems/bin/rackup:25:in `load'
        23: from /opt/dast/scnr-v1.5.1/.system/gems/gems/rack-2.2.3.1/bin/rackup:5:in `<top (required)>'
        22: from /opt/dast/scnr-v1.5.1/.system/gems/gems/rack-2.2.3.1/lib/rack/server.rb:168:in `start'
        21: from /opt/dast/scnr-v1.5.1/.system/gems/gems/rack-2.2.3.1/lib/rack/server.rb:311:in `start'
        20: from /opt/dast/scnr-v1.5.1/.system/gems/gems/rack-2.2.3.1/lib/rack/server.rb:379:in `handle_profiling'
        19: from /opt/dast/scnr-v1.5.1/.system/gems/gems/rack-2.2.3.1/lib/rack/server.rb:312:in `block in start'
        18: from /opt/dast/scnr-v1.5.1/.system/gems/gems/rack-2.2.3.1/lib/rack/server.rb:422:in `wrapped_app'
        17: from /opt/dast/scnr-v1.5.1/.system/gems/gems/rack-2.2.3.1/lib/rack/server.rb:249:in `app'
        16: from /opt/dast/scnr-v1.5.1/.system/gems/gems/rack-2.2.3.1/lib/rack/server.rb:349:in `build_app_and_options_from_config'
        15: from /opt/dast/scnr-v1.5.1/.system/gems/gems/rack-2.2.3.1/lib/rack/builder.rb:66:in `parse_file'
        14: from /opt/dast/scnr-v1.5.1/.system/gems/gems/rack-2.2.3.1/lib/rack/builder.rb:105:in `load_file'
        13: from /opt/dast/scnr-v1.5.1/.system/gems/gems/rack-2.2.3.1/lib/rack/builder.rb:116:in `new_from_string'
        12: from /opt/dast/scnr-v1.5.1/.system/gems/gems/rack-2.2.3.1/lib/rack/builder.rb:116:in `eval'
        11: from /opt/dast/scnr-v1.5.1/.system/scnr-ui-pro/config.ru:3:in `block in <main>'
        10: from /opt/dast/scnr-v1.5.1/.system/scnr-ui-pro/config.ru:3:in `require_relative'
         9: from /opt/dast/scnr-v1.5.1/.system/scnr-ui-pro/config/environment.rb:2:in `<top (required)>'
         8: from /opt/dast/scnr-v1.5.1/.system/scnr-ui-pro/config/environment.rb:2:in `RGLoader_load'
         7: from /opt/dast/scnr-v1.5.1/.system/scnr-ui-pro/config/environment.rb:2:in `<encoded>'
         6: from /opt/dast/scnr-v1.5.1/.system/scnr-ui-pro/config/environment.rb:2:in `require_relative'
         5: from /opt/dast/scnr-v1.5.1/.system/scnr-ui-pro/config/application.rb:2:in `<top (required)>'
         4: from /opt/dast/scnr-v1.5.1/.system/scnr-ui-pro/config/application.rb:2:in `RGLoader_load'
         3: from /opt/dast/scnr-v1.5.1/.system/scnr-ui-pro/config/application.rb:9:in `<encoded>'
         2: from /opt/dast/scnr-v1.5.1/.system/gems/gems/ecsypno-license-client-0.1.0/lib/ecsypno/license.rb:53:in `guard!'
         1: from /opt/dast/scnr-v1.5.1/.system/gems/gems/ecsypno-license-client-0.1.0/lib/ecsypno/license.rb:70:in `load'
/opt/dast/scnr-v1.5.1/.system/gems/gems/ecsypno-license-client-0.1.0/lib/ecsypno/license.rb:70:in `final': bad decrypt (OpenSSL::Cipher::CipherError)
Traceback (most recent call last):
        40: from /opt/dast/scnr-v1.5.1/bin/../.system/gems/bin/bundle:25:in `<main>'
        39: from /opt/dast/scnr-v1.5.1/bin/../.system/gems/bin/bundle:25:in `load'
        38: from /opt/dast/scnr-v1.5.1/.system/gems/gems/bundler-2.4.22/exe/bundle:29:in `<top (required)>'
        37: from /opt/dast/scnr-v1.5.1/.system/gems/gems/bundler-2.4.22/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        36: from /opt/dast/scnr-v1.5.1/.system/gems/gems/bundler-2.4.22/exe/bundle:37:in `block in <top (required)>'
        35: from /opt/dast/scnr-v1.5.1/.system/gems/gems/bundler-2.4.22/lib/bundler/cli.rb:28:in `start'
        34: from /opt/dast/scnr-v1.5.1/.system/gems/gems/bundler-2.4.22/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
        33: from /opt/dast/scnr-v1.5.1/.system/gems/gems/bundler-2.4.22/lib/bundler/cli.rb:34:in `dispatch'
        32: from /opt/dast/scnr-v1.5.1/.system/gems/gems/bundler-2.4.22/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
        31: from /opt/dast/scnr-v1.5.1/.system/gems/gems/bundler-2.4.22/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        30: from /opt/dast/scnr-v1.5.1/.system/gems/gems/bundler-2.4.22/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
        29: from /opt/dast/scnr-v1.5.1/.system/gems/gems/bundler-2.4.22/lib/bundler/cli.rb:492:in `exec'
        28: from /opt/dast/scnr-v1.5.1/.system/gems/gems/bundler-2.4.22/lib/bundler/cli/exec.rb:23:in `run'
        27: from /opt/dast/scnr-v1.5.1/.system/gems/gems/bundler-2.4.22/lib/bundler/cli/exec.rb:58:in `kernel_load'
        26: from /opt/dast/scnr-v1.5.1/.system/gems/gems/bundler-2.4.22/lib/bundler/cli/exec.rb:58:in `load'
        25: from /opt/dast/scnr-v1.5.1/.system/gems/bin/rackup:25:in `<top (required)>'
        24: from /opt/dast/scnr-v1.5.1/.system/gems/bin/rackup:25:in `load'
        23: from /opt/dast/scnr-v1.5.1/.system/gems/gems/rack-2.2.3.1/bin/rackup:5:in `<top (required)>'
        22: from /opt/dast/scnr-v1.5.1/.system/gems/gems/rack-2.2.3.1/lib/rack/server.rb:168:in `start'
        21: from /opt/dast/scnr-v1.5.1/.system/gems/gems/rack-2.2.3.1/lib/rack/server.rb:311:in `start'
        20: from /opt/dast/scnr-v1.5.1/.system/gems/gems/rack-2.2.3.1/lib/rack/server.rb:379:in `handle_profiling'
        19: from /opt/dast/scnr-v1.5.1/.system/gems/gems/rack-2.2.3.1/lib/rack/server.rb:312:in `block in start'
        18: from /opt/dast/scnr-v1.5.1/.system/gems/gems/rack-2.2.3.1/lib/rack/server.rb:422:in `wrapped_app'
        17: from /opt/dast/scnr-v1.5.1/.system/gems/gems/rack-2.2.3.1/lib/rack/server.rb:249:in `app'
        16: from /opt/dast/scnr-v1.5.1/.system/gems/gems/rack-2.2.3.1/lib/rack/server.rb:349:in `build_app_and_options_from_config'
        15: from /opt/dast/scnr-v1.5.1/.system/gems/gems/rack-2.2.3.1/lib/rack/builder.rb:66:in `parse_file'
        14: from /opt/dast/scnr-v1.5.1/.system/gems/gems/rack-2.2.3.1/lib/rack/builder.rb:105:in `load_file'
        13: from /opt/dast/scnr-v1.5.1/.system/gems/gems/rack-2.2.3.1/lib/rack/builder.rb:116:in `new_from_string'
        12: from /opt/dast/scnr-v1.5.1/.system/gems/gems/rack-2.2.3.1/lib/rack/builder.rb:116:in `eval'
        11: from /opt/dast/scnr-v1.5.1/.system/scnr-ui-pro/config.ru:3:in `block in <main>'
        10: from /opt/dast/scnr-v1.5.1/.system/scnr-ui-pro/config.ru:3:in `require_relative'
         9: from /opt/dast/scnr-v1.5.1/.system/scnr-ui-pro/config/environment.rb:2:in `<top (required)>'
         8: from /opt/dast/scnr-v1.5.1/.system/scnr-ui-pro/config/environment.rb:2:in `RGLoader_load'
         7: from /opt/dast/scnr-v1.5.1/.system/scnr-ui-pro/config/environment.rb:2:in `<encoded>'
         6: from /opt/dast/scnr-v1.5.1/.system/scnr-ui-pro/config/environment.rb:2:in `require_relative'
         5: from /opt/dast/scnr-v1.5.1/.system/scnr-ui-pro/config/application.rb:2:in `<top (required)>'
         4: from /opt/dast/scnr-v1.5.1/.system/scnr-ui-pro/config/application.rb:2:in `RGLoader_load'
         3: from /opt/dast/scnr-v1.5.1/.system/scnr-ui-pro/config/application.rb:9:in `<encoded>'
         2: from /opt/dast/scnr-v1.5.1/.system/gems/gems/ecsypno-license-client-0.1.0/lib/ecsypno/license.rb:53:in `guard!'
         1: from /opt/dast/scnr-v1.5.1/.system/gems/gems/ecsypno-license-client-0.1.0/lib/ecsypno/license.rb:70:in `load'
/opt/dast/scnr-v1.5.1/.system/gems/gems/ecsypno-license-client-0.1.0/lib/ecsypno/license.rb:70:in `final': bad decrypt (OpenSSL::Cipher::CipherError)

**Comment by Zapotek** [comment]
Hello,

Looks like a corrupted license file, you may need to reacquire one from the website.
I'm guessing it was for the Trial edition?

Cheers!

**Comment by sanholy** [comment]
thanks for reply.
What do you mean "a acorrupted license file"?
I just copy the key into ~/.scnr/license_key 
1、echo -n "BCA4K1T2V3MEJR089Y****" > ~/.scnr/license_key 
2、 excute  bash -c “$(curl -sSL https://get.ecsypno.com/scnr)”

**Comment by sanholy** [comment]
thank you . I will try it later
