### ISSUE TITLE
Docker build fails on MacOS

### ISSUE THREAD

**Issue by delfuego** [scnr/installer#43]
The [Docker build/run process](https://github.com/scnr/installer?tab=readme-ov-file#docker-installation) fails on MacOS.

If I just follow the directions as on the above-linked page, the first failure I get is that the build platform doesn't match the run platform:

```
 ! app The requested image's platform (linux/amd64) does not match the detected host
platform (linux/arm64/v8) and no specific platform was requested
```

I can get past this by adding the platform to the `app` service in the `docker-compose.yml` file:

```
services:
  app:
    build:
      dockerfile: Dockerfile
      platforms:
        - linux/arm64/v8
```

but then I also get an error that it can't bind-mount the `/etc/timezone` file, since that file doesn't exist on MacOS:

```
error during container init: error mounting "/etc/timezone" to rootfs at "/etc/timezone": create
mount destination for /etc/timezone mount: cannot mkdir in /var/lib/docker/overlay2/0698d9e0052a4c3cfb325b93085db78799b1afacff3c98176fb9cac16cdd0c0c
/merged/etc/timezone: not a directory: unknown: Are you trying to mount a directory onto
a file (or vice-versa)? Check if the specified host path exists and is the expected type
```

**Comment by Zapotek** [comment]
Hello,

Which version of Mac OS X are you using?

Best regards

**Comment by delfuego** [comment]
Apologies; that's obviously important data that I omitted!

macOS 14.7 (build 23H124), running on Apple Silicon (M3 Max).

**Comment by Zapotek** [comment]
Can you please also provide the output of:

```
docker -v
docker-compose -v
```

I'm on Mac OS X 15 but with the same machine without getting the issue.

**Comment by corrosive4354** [comment]
Use conditional logic in docker-compose.yml to check if the file exists and then decide whether to mount it.

In addition, it may be a compatibility issue between docker and mac. You can use [servbay](servbay.com) to solve it. It is more useful than docker on mac.

**Comment by Zapotek** [comment]
I believe this is a Docker version issue.

The platform shouldn't be changed as Codename SCNR requires AMD64, which Docker can handle on ARM64, so the platform warning isn't an issue.

About the missing files, they are indeed missing on OSX but with my Docker version Docker doesn't complain.

```
Mac:installer zapotek$ docker -v
Docker version 27.2.0, build 3ab4256
Mac:installer zapotek$ docker-compose -v
Docker Compose version v2.29.2-desktop.2
```

**Comment by Zapotek** [comment]
Regardless, I've updated the Dockerfile and Compose files to work now, timezone defaults to UTC.

**Comment by delfuego** [comment]
Apologies; I've been out of pocket for the past 48h.

```
$ docker -v
Docker version 27.3.1, build ce12230
$ docker-compose -v
Docker Compose version v2.29.7
```
