### ISSUE TITLE
--plugin=exec:during not working like Arachni

### ISSUE THREAD

**Issue by CollabDSO** [scnr/installer#6]
I am trying to run a python code with SCNR as follows - 

./scnr --plugin=exec:during="python /path/to/file/PythonFile.py" http://<URL TO SCAN>/ --platform=linux

But, the above Python file is not getting executed. This used to get executed with Arachni.
Kindly let me know if SCNR has support for "--plugin=exec:during".

**Comment by Zapotek** [comment]
Fixed, thanks for the feedback. :)

**Comment by CollabDSO** [comment]
Can you pls send me the build for this fix? Also, pls let me know, for future, from where can I access these builds directly without having to bother you?

**Comment by Zapotek** [comment]
Please check the README if you want to manually install builds.

**Comment by CollabDSO** [comment]
Got it....thank you so much
