### ISSUE TITLE
SCNR unable to scan web application hosted on a particular port

### ISSUE THREAD

**Issue by CollabDSO** [scnr/installer#7]
I am trying to run a simple command - 

./scnr http://localhost:3000/

But SCNR throws the below error:
[-] Retrying for: http://172.31.3.192:3000/ [Server returned nothing (no headers, no data)]
 [-] Retrying for: http://172.31.3.192:3000/ [Server returned nothing (no headers, no data)]
 [-] Retrying for: http://172.31.3.192:3000/ [Server returned nothing (no headers, no data)]
 [-] Retrying for: http://172.31.3.192:3000/ [Server returned nothing (no headers, no data)]
 [-] Retrying for: http://172.31.3.192:3000/ [Server returned nothing (no headers, no data)]
 [-] [/home/ubuntu/scnr-1.0dev-1.0dev-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/framework/parts/data.rb#pop_page_from_url_queue:153] Giving up trying to audit: http://172.31.3.192:3000/
 [-] [/home/ubuntu/scnr-1.0dev-1.0dev-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/framework/parts/data.rb#pop_page_from_url_queue:154] Couldn't get a response after 5 tries: Server returned nothing (no headers, no data).

The same web app is being scanned by Arachni perfectly. Kindly let me know if there is an issue with scanning web applications hosted on a particular port, because scans with web apps like http://localhost/DVWA (websites with folders and no ports) is working.

**Comment by Zapotek** [comment]
Hello,

There's no such issue AFAIK.
I use custom ports like that for testing all the time.

Is there a way that I can get access to that server in order to debug the issue?

Cheers

**Comment by CollabDSO** [comment]
I have brought the server up. Please use the following URL:

http://13.233.96.67:3000

**Comment by Zapotek** [comment]
Thank you very much, I was able to reproduce.
Looking into it.

**Comment by CollabDSO** [comment]
should I take a new build of SCNR from git for this to work?

**Comment by Zapotek** [comment]
Yes there's no update mechanism yet.

**Comment by CollabDSO** [comment]
I am not seeing any new updates on the git repo.

**Comment by Zapotek** [comment]
The updates were pushed to the [builds](https://downloads.ecsypno.com/).

**Comment by CollabDSO** [comment]
Thank you so much...it is working now!!
