### ISSUE TITLE
Can not export report from Pro Web UI

### ISSUE THREAD

**Issue by mdwaliulahmed** [scnr/installer#8]
There is no option for exporting SCNR report  from SCNR Pro WebUI

**Comment by Zapotek** [comment]
Done!

**Comment by mdwaliulahmed** [comment]
Thanks but where can I find that option?

Still couldn't find the option like the Arachni.

**Comment by mdwaliulahmed** [comment]
Thanks a lot. 

I have become a big fan of SCNR

**Comment by Zapotek** [comment]
If you go to a completed scan revision a new tab will appear in the end called "Export".

This will work for new scans though, report files weren't associated with scan revisions previously.

I'm still thinking about what to do for the unified overview export, per scan not per revision.
I guess just exporting the report of the last revision will do, but I'm going over things again to make sure.

**Comment by mdwaliulahmed** [comment]
Solved! You're doing a great job! Keep it up.

**Comment by QuanPham247** [comment]
> Solved! You're doing a great job! Keep it up.

Hey man, how did you start the scan on Web UI. I schedule a scan to start ASAP but could not get it to start.
